### ISSUE TITLE
Can this work with a UITableView?

### ISSUE THREAD

**Issue by arinasawa** [Touchwonders/Transition#12]

**Comment by toineheuvelmans** [comment]
It’s for ViewControllers, but the transition of course is between views. A UITableView is also a view, so if it is the view of a ViewController (e.g. a UITableViewController) it should work. That said, it depends on what you want to do, if Transition can provide what you want.

**Comment by arinasawa** [comment]
I want to transition from a table view cell to a detail view controller when a user taps a cell. Can I use the transition library for that?

**Comment by toineheuvelmans** [comment]
That should be possible, using a [shared element](https://github.com/Touchwonders/Transition/blob/master/Documentation/shared_element.md). You can snapshot the cell that needs to transition, then animate the snapshot. The [NavigationTransitionsExample](https://github.com/Touchwonders/Transition/tree/master/Examples/NavigationTransitionsExample) uses shared elements with a `UICollectionView` instead of a `UITableView`, so that should be comparable.
