### ISSUE TITLE
Interactive Modal using Pan crashes on Dismiss

### ISSUE THREAD

**Issue by jtressle** [Touchwonders/Transition#5]
Hi,

Great library.  I'm trying to do a simple interactive modal transition.  I'm using PanInteractionController(forModalTransitionsAtEdge...) and the TransitionController(forInteractiveModalPresentationsFrom...) to setup the interactionController and transitionController.  Presenting works fine.

When I try to dismiss the view by flicking upwards, I get "fatal error: unexpectedly found nil while unwrapping an Optional value" in "UIViewControllerContextTransitioning+Properties.swift".  Basically "toView" is nil here:

`        case .dismiss:
            if toView.superview == nil {
                containerView.insertSubview(toView, belowSubview: fromView)
            }`

Is this an issue, or am I not setting up the transition controller correctly.

Thanks.
Jan-Michael

PS: Here's the code to produce the issue.  The StickerViewController is just a view with a UILabel.

import UIKit
import Transition

class ViewController: UIViewController
{
    private(set) var transitionController: TransitionController!
    private(set) var interactionController: PanInteractionController!
    
    fileprivate weak var stickerViewController: StickerViewController?
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.view.backgroundColor = UIColor.red
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        if interactionController == nil
        {
            self.interactionController = PanInteractionController(forModalTransitionsAtEdge: .top)
            self.transitionController = TransitionController(forInteractiveModalPresentationsFrom: self, transitionsSource: self, interactionController: interactionController)
        }
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}

extension ViewController : TransitionsSource
{
    // proivide transition for presentation / dismissal
    func transitionFor(operationContext: TransitionOperationContext, interactionController: TransitionInteractionController?) -> Transition
    {
        //animation
        let transitionAnimation = MoveTransitionAnimation(forModalTransitionsAtEdge: .top)
        let transition = Transition(duration: 0.4, animation: transitionAnimation)
        return transition
    }
}

extension ViewController : InteractiveModalTransitionOperationDelegate
{
    func viewControllerForInteractiveModalPresentation(by sourceViewController: UIViewController, gestureRecognizer: UIGestureRecognizer) -> UIViewController
    {
        let vc = self.storyboard?.instantiateViewController(withIdentifier: "sticker")
        vc?.modalPresentationStyle = .overCurrentContext
        vc?.transitioningDelegate = self as? UIViewControllerTransitioningDelegate
        
        self.stickerViewController = vc as? StickerViewController
        return vc!
    }
}

**Comment by jtressle** [comment]
Hi, 

I believe I found the issue.  The function 'defaultViewSetup(for modalOperation:' assumes the UIViewControllerContextTransitioning context toView key is not nil when dismissing.  However, the UIKit context object stores a nil for 'fromView' when presenting, and a nil for 'toView' when dismissing.  The defaultViewSetup code breaks down because of this.  I created a workaround by doing the following.  Not sure if this is correct:

`        let _toView = toViewController.view
        let _fromView = fromViewController.view
        let _superview = _toView?.superview
        
        switch modalOperation {
        case .present:
            containerView.addSubview(toView)
        case .dismiss:
            
            if (_superview == nil)
            {
                containerView.insertSubview(_toView!, belowSubview: _fromView!)
            }
        default: return nil
        }
        
        _toView?.frame = finalFrame(for: toViewController)
        return modalOperation == .present ? _toView : _fromView`

Thoughts?

Thanks,
Jan-Michael

**Comment by toineheuvelmans** [comment]
Hi @jtressle , first of all apologies for the delayed response, I just got a little 👶 so I didn't get to coding matters for a while.
I haven't yet checked what you describe but it sounds plausible. Your code example seems fine, and I must admit that the `defaultViewSetup()` function was a bit of an afterthought, just to make the examples a bit more legible. When developing it, I noticed indeed that the properties weren't always what you'd logically expect. Given your suggestion, do I read correctly that although the `toView` is nil, the `toViewController` can be non-nil? (and similarly for the `from` counterparts) That would really surprise me.

Either way, the logic that I tried implementing is: if we're dismissing, and the view that will be shown (the `toView`, being the view visible when we initiated presenting) is available but is NOT in the view hierarchy (it doesn't have a superview), than we need to add it in the containerView, under the currently visible view (the `fromView`).

Your suggested fix will still crash when `toView` is nil, because then `_superview` will also be nil, after which you force-unwrap `_toView` to insert it.

I'm thinking out loud here, and as said have not yet tested this scenario. Have you made any progress or gained insights in the past few days?

**Comment by toineheuvelmans** [comment]
I finally had the time to address this issue. I used the ModalTransitionsExample as testing project, and indeed when I replace DropTargetViewAnimation.swift line 57:

```
dropTargetView = operation.isPresenting ? transitionContext.toView : transitionContext.fromView
```

with this:

```
dropTargetView = transitionContext.defaultViewSetup(for: operationContext.operation)
```

The app will crash on dismissal, due to a force-unwrapped `fromView` was nil. Quite odd if you think about it, because the `fromViewController` is not nil, but the `fromView` is.
The fix that I applied is simple:
```
public var fromView: UIView! {
    return self.view(forKey: .from)
}
```
now is this:
```
public var fromView: UIView! {
    return self.view(forKey: .from) ?? fromViewController.view
}
```

**Comment by jtressle** [comment]
@toineheuvelmans great and congrats on the baby!  I'll test it out this week.

Best,
Jan-Michael
